Q1

In [ ]:
import numpy as np
my_array = np.array([[1,2,3],[4,5,6]])
new_list=my_array.tolist()
new_list

[[1, 2, 3], [4, 5, 6]]

Q2

ma methode (eye)

In [ ]:
my_tab1 = my_tab2 = np.eye(5)
my_tab2 = np.eye(5)
print(my_tab1 + my_tab2)

[[2. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0.]
 [0. 0. 2. 0. 0.]
 [0. 0. 0. 2. 0.]
 [0. 0. 0. 0. 2.]]


methode 1

In [ ]:
s = np.trace(my_array)
s

6

methode 2

In [ ]:
val_diagonal = my_array.diagonal()
s=0
for i in range(len(val_diagonal)):
  s = s + val_diagonal[i]
s

6

Q3
---



---



In [ ]:
a=np.array([[1,2,3],[4,5,6]])
x=2
for i in range(a.shape[0]):
  for j in range(a.shape[1]):
    if a[i][j] > x:
            print(a[i][j] ,"is higher than", x)

3 is higher than 2
4 is higher than 2
5 is higher than 2
6 is higher than 2


Q4

In [ ]:
my_array1 = np.array([[1,2,3],[4,5,6]])
my_array2 = np.array([[6,5,4],[3,2,1]])
print(my_array1 + my_array2)

[[7 7 7]
 [7 7 7]]


Q5

In [ ]:
my_tab = np.array([[1,2,3],[4,5,6]])
m = np.mean(tab,axis = 1)
m

NameError: ignored